DELETE FROM Products
WHERE FarmerId NOT IN (SELECT Id FROM Farmers);

SELECT * FROM Products
WHERE FarmerId NOT IN (SELECT Id FROM Farmers);

DELETE FROM Products
WHERE FarmerId NOT IN (SELECT Id FROM Farmer

SELECT * FROM Products
WHERE FarmerId NOT IN (SELECT Id FROM Farmers);

DELETE FROM Products
WHERE FarmerId NOT IN (SELECT Id FROM Farmers);