SELECT Id, FullName, UserId FROM Farmers;
SELECT Id FROM AspNetUsers;

DROP DATABASE AgriEnergyDB;

ALTER DATABASE [AgriEnergyDB] SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
DROP DATABASE [AgriEnergyDB];

USE master;
GO

ALTER DATABASE [AgriEnergyDB] SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
GO

DROP DATABASE [AgriEnergyDB];
GO